- hosts: localhost
  user: ubuntu
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', '{{app_name}}/{{service_name}}/deployment.yml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', '{{app_name}}/{{service_name}}/service.yml') | from_yaml }}"
  - name: Deploy the Ingress
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', '{{app_name}}/common/ingress.yml') | from_yaml }}"
