- name : Playbook to schedule cloudwatch script as cron
  hosts: all
  user: ubuntu
  sudo: yes
  gather_facts: True

  vars:
    war_file: samplenew.war
    tomcat_war_path: /opt/tomcat/webapps

  tasks:
    - name: Deploy war | Install necessary packages if missing
      apt:
        name: python3-pip
        state: present
   
    - name: Deploy war | Install python packages
      pip:
        name:
        - boto3
        - botocore
        
    - name: Deploy war | Download war from AWS S3
      s3:
        bucket: projcts-artifacts
        object: "{{jobname}}-{{buildno}}/jobs/{{jobname}}/{{buildno}}/{{war_file}}"
        dest: "/tmp/{{war_file}}"
        mode: get

    - name: Deploy war | Copy war file to tomcat webapps
      copy:
        src: /tmp/{{war_file}}
        dest: "{{tomcat_war_path}}/{{war_file}}"
        owner: tomcat
        group: tomcat
        mode: '0644'
        backup: yes
        
    - name: Deploy war | Restart tomcat service
      service:
        name: tomcat
        state: restarted
