###### ansible-playbook -i <IP>, --extra-vars "host=all" -vvv schedule_cron.yml

- name : Playbook to schedule cloudwatch script as cron
  hosts: "{{host}}"
  user: admin
  sudo: yes
  gather_facts: True

  vars:
    script_dir: /home/infrastructure/scripts/

  tasks:
    - name: Install boto3 and other supporting packages
      become: yes
      pip:
        executable: pip2
        name: "{{ item }}"
      with_items:
        - boto3
        - psutil
        - requests

    - name: Check if jq is installed
      block:
        - name: Check if jq is installed
          command: dpkg-query -l jq
          register: check_pkg
      rescue:
        - debug: "msg={{ check_pkg }}"

    - name: Install jq
      package: 
        name: jq
        state: present
      when: check_pkg.rc == 1

    - name: Check if directory exists
      file:
        path: "{{ script_dir }}" 
        state: directory
        owner: admin
        group: admin
        mode: 0755

    - name: Copy script to the correct path
      copy:
        src: /opt/infrastructure/scripts/script.py 
        dest: "{{ script_dir }}" 
        owner: admin
        group: admin
        mode: 0755

    - name: Create cronjob and schedule
      cron:
        name: script
        minute: "*/5"
        user: admin
        job: "{{ script_dir }}script.py"
