- name: Configure rabbitmq_users | create rabbitmq users
  rabbitmq_user:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    vhost: "{{ item['vhost']|default(omit) }}"
    configure_priv: "{{ item['configure_priv']|default(omit) }}"
    read_priv: "{{ item['read_priv']|default(omit) }}"
    write_priv: "{{ item['write_priv']|default(omit) }}"
    tags: "{{ item['tags']|default(omit) }}"
    permissions: "{{ item['permissions']|default(omit) }}"
    state: present
  run_once: yes
  delegate_to: "{{ master }}"
  become: true
  with_items: "{{ rabbitmq_users }}"
