apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping-app
  name: shopping-app-deloyment-service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-app
      service: service1
  template:
    metadata:
      labels:
        app: shopping-app
        service: service1
    spec:
      containers:
      - name: shopping-app-service-1
        image: "{{ image_id }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: dockerhubsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
