
- name: Install Docker | Add official Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Install Docker | Add official Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker-official'
    update_cache: yes

- name: Install Docker | Install docker-ce and docker-compose
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

- name: Install Docker | Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker | Add users to the Docker group
  user:
    name: "{{ system_user }}"
    groups: docker
    append: yes
