apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}-service
spec:
  selector:
    app: "{{ app_name }}"
    task: "{{ service_name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
