apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ app_name }}"
  name: {{ service_name }}-deloyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ app_name }}"
      task: "{{ service_name }}"
  template:
    metadata:
      labels:
        app: "{{ app_name }}"
        task: "{{ service_name }}"
    spec:
      containers:
      - name: {{ service_name }}-pod
        image: "{{ image_id }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: dockerhubsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
