apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shoppingapp
  name: shoppingapp-home-deloyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingapp
      task: shoppingapp-home
  template:
    metadata:
      labels:
        app: shoppingapp
        task: shoppingapp-home
    spec:
      containers:
      - name: shoppingapp-home-pod
        image: "{{ image_id }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: dockerhubsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
