apiVersion: v1
kind: Service
metadata:
  name: shoppingapp-kids-service
spec:
  selector:
    app: shoppingapp
    task: shoppingapp-kids
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
